name: Create release

on:
  workflow_run:
    workflows: ["Build distributions"]
    branches: [master]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          run_id: ${{github.event.workflow_run.id}}
          workflow_conclusion: success
      - name: helper
        run: |
          ls *
          exit 1

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{env.TAGNAME}}
          release_name: ${{env.RELEASENAME}}
          body_path: data/release-changelog.txt
          draft: false
          prerelease: ${{env.PRERELEASE}}