name: Create release

on:
  workflow_run:
    workflows: ["Build distributions"]
    branches: [master]
    types:
      - completed

jobs:
  verify:
    outputs:
      status: ${{steps.early.conclusion}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: latest-tag
        with:
          semver_only: true
      - name: Verify version
        id: early
        run: |
          if [[ "${{steps.latest-tag.outputs.tag}}" == "$(cat data/version.txt)" ]]; then
            exit 1
          else
            exit 0
          fi
  release:
    needs: verify
    if: needs.verify.outputs.status == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          run_id: ${{github.event.workflow_run.id}}
          workflow_conclusion: success
          skip_unpack: true
      - name: helper
        run: |
          ls
          echo ---
          ls *
          exit 1
          echo "TAGNAME=$(cat data/version.txt)" >> $GITHUB_ENV
          echo "RELEASENAME=googium $(cat data/version.txt)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{env.TAGNAME}}
          release_name: ${{env.RELEASENAME}}
          body_path: data/release-changelog.txt
          draft: false
          prerelease: false